#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 10**9)  # TODO: edit here
    M = random.randint(1, 1000)  # TODO: edit here
    T = [None for _ in range(M)]
    P = [None for _ in range(M)]
    for i in range(M):
        T[i] = random.randint(1, 10**9)  # TODO: edit here
        P[i] = random.randint(1, 10**9)  # TODO: edit here
    Q = random.randint(1, 1000)  # TODO: edit here
    A = [None for _ in range(Q)]
    B = [None for _ in range(Q)]
    for i in range(Q):
        A[i] = random.randint(1, 10**9)  # TODO: edit here
        B[i] = random.randint(1, 10**9)  # TODO: edit here
    print(N, M)
    for i in range(M):
        print(T[i], P[i])
    print(Q)
    for i in range(Q):
        print(A[i], B[i])


if __name__ == "__main__":
    main()
