#!/usr/bin/env python3
# from typing import *


# def solve(R: int, C: int, K: int, s: List[str]) -> int:
def solve(R, C, K, s):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    R, C, K = map(int, input().split())
    s = [None for _ in range(R)]
    for i in range(R):
        s[i] = input()
    a = solve(R, C, K, s)
    print(a)


if __name__ == '__main__':
    main()
