#!/usr/bin/env python3
# from typing import *


# def solve(R: int, G: int, B: int) -> int:
def solve(R, G, B):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    R, G, B = map(int, input().split())
    a = solve(R, G, B)
    print(a)


if __name__ == '__main__':
    main()
