#!/usr/bin/env python3
# from typing import *


# def solve(s: str, k: int) -> int:
def solve(s, k):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    s = input()
    k = int(input())
    a = solve(s, k)
    print(a)


if __name__ == '__main__':
    main()
