#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 10)  # TODO: edit here
    S = [[None for _ in range(N)] for _ in range(2 * N + 2)]
    T = [[None for _ in range(N)] for _ in range(2 * N + 2)]
    for j in range(N + 2):
        for i in range(N):
            S[i + j][i] = random.randint(1, 10)  # TODO: edit here
    for j in range(N + 2):
        for i in range(N):
            T[i + j][i] = random.randint(1, 10)  # TODO: edit here
    print(N)
    for j in range(N + 2):
        print(*[S[i + j][i] for i in range(N)])
    for j in range(N + 2):
        print(*[T[i + j][i] for i in range(N)])


if __name__ == "__main__":
    main()
