#!/usr/bin/env python3
# from typing import *

MOD = 1000000007


# def solve(R: int, C: int, X: int, Y: int, D: int, L: int) -> int:
def solve(R, C, X, Y, D, L):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    R, C = map(int, input().split())
    X, Y = map(int, input().split())
    D, L = map(int, input().split())
    a = solve(R, C, X, Y, D, L)
    print(a)


if __name__ == '__main__':
    main()
