#!/usr/bin/env python3
# from typing import *


# def solve(N: int, X: int, K: int, P: List[int], U: List[int], C: List[int]) -> int:
def solve(N, X, K, P, U, C):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, X, K = map(int, input().split())
    P = [None for _ in range(N)]
    U = [None for _ in range(N)]
    C = [None for _ in range(N)]
    for i in range(N):
        P[i], U[i], C[i] = map(int, input().split())
    a = solve(N, X, K, P, U, C)
    print(a)


if __name__ == '__main__':
    main()
