#!/usr/bin/env python3
# from typing import *


# def solve(W: int, a: int, b: int) -> int:
def solve(W, a, b):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    W, a, b = map(int, input().split())
    a1 = solve(W, a, b)
    print(a1)


if __name__ == '__main__':
    main()
