#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 1000)  # TODO: edit here
    P = [None for _ in range(N - 1)]
    M = random.randint(1, 1000)  # TODO: edit here
    S = [None for _ in range(M)]
    T = [None for _ in range(M)]
    K = random.randint(1, 10**9)  # TODO: edit here
    for i in range(N - 1):
        P[i] = random.randint(1, 10**9)  # TODO: edit here
    for i in range(M):
        S[i] = random.randint(1, 10**9)  # TODO: edit here
        T[i] = random.randint(1, 10**9)  # TODO: edit here
    print(N, M, K)
    print(*[P[i] for i in range(N - 1)])
    for i in range(M):
        print(S[i], T[i])


if __name__ == "__main__":
    main()
