#!/usr/bin/env python3
# from typing import *


# def solve(X: int) -> int:
def solve(X):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X = int(input())
    if X%10 == 0:
        print(X//10)
    else:
        print(X//10+1)


if __name__ == '__main__':
    main()
