#include <iostream>
#include <string>
#include <vector>
#include <cstdlib> // abs()関数のために必要
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;




// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    long long A, M, L, R;
    std::cin >> A >> M >> L >> R;
    long long l = L + ((A-L) % M + M) % M;
    long long r = R - ((R-A) % M + M) % M;
    //int64_t l, r;
    //l = abs(((L - A) / M)) + 1;
    //r = abs(((R - A) / M)) + 1;
    
    //auto ans = solve(A, M, L, R);
    //if(R-L <M){
    //    std::cout << 0 << endl;
    //}
    //else{
    //    std::cout << abs((R - L)/M) + 1 << endl;
    //}

    std::cout << (r-l) / M + 1 << endl;
    

    return 0;
}
