#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <queue>
#include <array>
#include <climits>
#include <cmath>
#include <set>
#include <map>
#include <bitset>
#include <deque>
#include <numeric>
#include <assert.h>
#include <unordered_map>
#include <type_traits> // For std::is_floating_point
#include <cmath> // For std::ceil
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


std::pair<int64_t, int64_t> solve(int N, const std::vector<int64_t> &a) {
    set<int64_t> rates;
    int64_t cnt=0;
    REP(i, N){
        if(a[i]/400 < 8){
            rates.insert(a[i]/400);
            cerr << a[i]/400 << endl;
        }
        else{
            cnt++;
        }
    }

    if (rates.size() == 0) return {1, cnt};
    return {rates.size(), rates.size()+cnt};
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    std::cin >> N;
    std::vector<int64_t> a(N);
    REP (i, N) {
        std::cin >> a[i];
    }
    auto [d, e] = solve(N, a);
    std::cout << d << ' ' << e << '\n';
    return 0;
}
