#!/usr/bin/env python3
# from typing import *





# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B, W = map(int, input().split())
    INF = 10**18
    pmin = float('inf')
    pmax = -float('inf')
    temp = 0
    counter = (W*1000) // A
    while counter >= 0:
        print(counter)
        if ((W*1000 - (A * counter)) % B == 0):
            temp = counter+((W*1000 - (A * counter)) // B)
            pmin = min(pmin, temp)
            pmax = max(pmax, temp)
            print (pmin)
            print(pmax)
            print("***")
        counter -= 1

    if pmin == float('inf') and pmax == -float('inf'):
        print("UNSATISFIED")
    else:
        print(str(pmin) + " " + str(pmax))

if __name__ == '__main__':
    main()
