#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H = random.randint(1, 10)  # TODO: edit here
    W = random.randint(1, 10)  # TODO: edit here
    M = random.randint(1, 10)  # TODO: edit here
    X = [None for _ in range(M)]
    Y = [None for _ in range(M)]
    for i in range(M):
        X[i] = random.randint(1, 10)  # TODO: edit here
        Y[i] = random.randint(1, 10)  # TODO: edit here
    print(H, W, M)
    for i in range(M):
        print(X[i], Y[i])


if __name__ == "__main__":
    main()
