#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, A: List[int]) -> Tuple[str, List[str]]:
def solve(N, M, A):
    A.sort()
    cnt = N - M
    print(cnt)
    B = ""
    for num in range(N + 1):
        if num == 0:
            continue
        if num not in A:
            B += str(num) + " "
    return B


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    A = [None for _ in range(M)]
    for i in range(M):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    ans = solve(N, M, A)
    print(ans)

if __name__ == '__main__':
    main()
