#!/usr/bin/env python3
# from typing import *


# def solve(a: int, b: int, n: int) -> int:
def solve(a, b, n):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = int(input())
    b = int(input())
    n = int(input())
    a1 = solve(a, b, n)
    print(a1)


if __name__ == '__main__':
    main()
