#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = random.randint(1, 10**9)  # TODO: edit here
    b = random.randint(1, 10**9)  # TODO: edit here
    c = random.randint(1, 10**9)  # TODO: edit here
    d = random.randint(1, 10**9)  # TODO: edit here
    e = random.randint(1, 10**9)  # TODO: edit here
    f = random.randint(1, 10**9)  # TODO: edit here
    g = random.randint(1, 10**9)  # TODO: edit here
    h = random.randint(1, 10**9)  # TODO: edit here
    i = random.randint(1, 10**9)  # TODO: edit here
    j = random.randint(1, 10**9)  # TODO: edit here
    k = random.randint(1, 10**9)  # TODO: edit here
    l = random.randint(1, 10**9)  # TODO: edit here
    print(a, b, c, d, e, f)
    print(g, h, i, j, k, l)


if __name__ == "__main__":
    main()
