#!/usr/bin/env python3
# from typing import *


# def solve(A: int, B: int, C: int) -> Tuple[int, int, int]:
def solve(A, B, C):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A = int(input())
    B = int(input())
    C = int(input())
    d, e, f = solve(A, B, C)
    print(d)
    print(e)
    print(f)


if __name__ == '__main__':
    main()
