#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    sx = random.randint(1, 10**9)  # TODO: edit here
    sy = random.randint(1, 10**9)  # TODO: edit here
    tx = random.randint(1, 10**9)  # TODO: edit here
    ty = random.randint(1, 10**9)  # TODO: edit here
    print(sx, sy, tx, ty)


if __name__ == "__main__":
    main()
