#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <queue>
#include <array>
#include <climits>
#include <cmath>
#include <set>
#include <map>
#include <bitset>
#include <deque>
#include <numeric>
#include <assert.h>
#include <unordered_map>
#include <type_traits> // For std::is_floating_point
#include <cmath> // For std::ceil
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(int N, int64_t X, const std::vector<int64_t> &P, const std::vector<int64_t> &B, const std::vector<int64_t> &W, const std::vector<int64_t> &C) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    int64_t X;
    std::cin >> N;
    std::vector<int64_t> P(N - 1), B(N), W(N), C(N);
    std::cin >> X;
    REP (i, N - 1) {
        std::cin >> P[i];
    }
    REP (i, N) {
        std::cin >> B[i] >> W[i] >> C[i];
    }
    auto ans = solve(N, X, P, B, W, C);
    REP (i, N) {
        std::cout << ans[i] << '\n';
    }
    return 0;
}
