#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <queue>
#include <array>
#include <climits>
#include <cmath>
#include <set>
#include <map>
#include <bitset>
#include <deque>
#include <numeric>
#include <assert.h>
#include <unordered_map>
#include <type_traits> // For std::is_floating_point
#include <cmath> // For std::ceil
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;



// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    std::string t; cin >> t;
    int64_t n; cin >> n;
    vector<vector<string>> a(n);
    REP(i, n){
        int64_t k; cin >> k;
        a[i].resize(k);
        REP(j, k){
            cin >> a[i][j];
        }
    }
    int64_t INF = 1LL<<60;
    vector<vector<int64_t>> dp(n+1, vector<int64_t>(t.size()+1, INF));
    dp[0][0] = 0;
    REP(i, n){
        REP(j, t.size()+1) dp[i+1][j] = dp[i][j];

        REP(j, t.size()+1){
            for(auto &s : a[i]){
                if(j + s.size() > t.size()) continue;

                bool ok = true;
                REP(k, s.size()){
                    if(t[j+k] != s[k]) ok = false;
                }

                if(ok){
                    dp[i+1][j + s.size()] =
                        min(dp[i+1][j + s.size()], dp[i][j] + 1);
                }
            }
        }
    }
    if(dp[n][t.size()] == INF){
        cout << -1 << "\n";
    }
    else{
        cout << dp[n][t.size()] << "\n";
    }
    return 0;
}
