#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random
import string

def generate_random_string(length):
    # 英大文字と英小文字からなる文字列を生成
    letters = string.ascii_letters
    # 文字列をシャッフルしてランダムな順序で取得
    random_string = ''.join(random.choice(letters) for _ in range(length))
    return random_string



# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # 長さが1以上のランダムな文字列を生成
    random_string = generate_random_string(random.randint(1, 100))
    print(random_string)


    '''
    S = ''.join([random.choice('abcde') for _ in range(random.randint(1, 100))])  # TODO: edit here
    print(S)
    '''
if __name__ == "__main__":
    main()
