#!/usr/bin/env python3
# from typing import *

# def solve(S: str) -> str:
def solve(S):
    temp = 0
    if S[0].isupper():
        if len(S) == 1:
            check = "Yes"
        else:
            if S[1:].islower():
                check = "Yes"
            else:
                check = "No"
    else:
        check = "No"
    return check

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)

if __name__ == '__main__':
    main()
