#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 1000)  # TODO: edit here
    a = [None for _ in range(N - 1)]
    b = [None for _ in range(N - 1)]
    for i in range(N - 1):
        a[i] = random.randint(1, 10**9)  # TODO: edit here
        b[i] = random.randint(1, 10**9)  # TODO: edit here
    Q = random.randint(1, 1000)  # TODO: edit here
    t = [None for _ in range(Q)]
    e = [None for _ in range(Q)]
    x = [None for _ in range(Q)]
    for i in range(Q):
        t[i] = random.randint(1, 10**9)  # TODO: edit here
        e[i] = random.randint(1, 10**9)  # TODO: edit here
        x[i] = random.randint(1, 10**9)  # TODO: edit here
    print(N)
    for i in range(N - 1):
        print(a[i], b[i])
    print(Q)
    for i in range(Q):
        print(t[i], e[i], x[i])


if __name__ == "__main__":
    main()
