#!/usr/bin/env python3
# from typing import *


# def solve(m: int) -> str:
def solve(m):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    m = int(input())
    a = solve(m)
    print(a)


if __name__ == '__main__':
    main()
