#!/usr/bin/env python3
# from typing import *


# def solve(W: int, H: int, N: int, X: List[int], Y: List[int]) -> int:
def solve(W, H, N, X, Y):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    W, H = map(int, input().split())
    N = int(input())
    X = [None for _ in range(N)]
    Y = [None for _ in range(N)]
    for i in range(N):
        X[i], Y[i] = map(int, input().split())
    a = solve(W, H, N, X, Y)
    print(a)


if __name__ == '__main__':
    main()
