#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    u = [None for _ in range(NK - 1)]
    v = [None for _ in range(NK - 1)]
    N = random.randint(1, 10)  # TODO: edit here
    K = random.randint(1, 10)  # TODO: edit here
    for i in range(NK - 1):
        u[i] = random.randint(1, 10)  # TODO: edit here
        v[i] = random.randint(1, 10)  # TODO: edit here
    print(N, K)
    for i in range(NK - 1):
        print(u[i], v[i])


if __name__ == "__main__":
    main()
