#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(int N, const std::vector<std::string> &S) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t n;
    std::cin >> n;
    std::vector<std::string> S(n);
    REP (i, n) {
        std::cin >> S[i];
    }
    vector<int64_t> yoko(n, 0);
    vector<int64_t> tate(n, 0);
    REP(i, n){
        REP(j, n){
            if(S[i][j] == 'o'){
                yoko[i]++;
                tate[j]++;
            }
        }
    }
    int64_t ans = 0;

    REP(i, n){
        REP(j, n){
            if(S[i][j] == 'o'){
                ans += (yoko[i] - 1) * (tate[j] - 1);
            }
        }
    }

    std::cout << ans << '\n';
    return 0;
}
