#!/usr/bin/env python3
# from typing import *

def nth_base_5(n):
    # 5進数の文字列を生成するための再帰関数
    if n < 5:
        return str(n)
    else:
        return nth_base_5(n // 5) + str(n % 5)

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input()) - 1
    ans = nth_base_5(N)
    dic = {"0": "0", "1": "2", "2": "4", "3": "6", "4": "8"}
    print("".join(str(dic[c]) for c in ans))
if __name__ == '__main__':
    main()
