#!/usr/bin/env python3
# from typing import *


# def solve(N: int, G: int, E: int, p: List[int], a: List[int], b: List[int]) -> int:
def solve(N, G, E, p, a, b):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    G = int(next(tokens))
    E = int(next(tokens))
    p = [None for _ in range(G)]
    a = [None for _ in range(E)]
    b = [None for _ in range(E)]
    for i in range(G):
        p[i] = int(next(tokens))
    for i in range(E):
        a[i] = int(next(tokens))
        b[i] = int(next(tokens))
    assert next(tokens, None) is None
    a1 = solve(N, G, E, p, a, b)
    print(a1)


if __name__ == '__main__':
    main()
