#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random
import string

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # Constraints
    MAX_N = 2 * 10**5
    MAX_Q = 2 * 10**5

    # Generate N
    N = random.randint(1, MAX_N)

    # Generate a random string S of length N with lowercase letters
    S = ''.join(random.choices(string.ascii_lowercase, k=N))

    # Generate Q
    Q = random.randint(1, MAX_Q)

    # Generate Q pairs of lowercase letters ci, di
    cd_pairs = [(random.choice(string.ascii_lowercase), random.choice(string.ascii_lowercase)) for _ in range(Q)]

    # Print the input in the specified format
    print(N)
    print(S)
    print(Q)
    for ci, di in cd_pairs:
        print(ci, di)

if __name__ == "__main__":
    main()
