#!/usr/bin/env python3
# from typing import *



# def solve(N: int, S: str, Q: int, c: List[str], d: List[str]) -> str:


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = input()
    Q = int(input())
    m = {x: x for x in "qwertyuiopasdfghjklzxcvbnm"}
    
    for _ in range(Q):
        c, d = input().split()
        for k, v in m.items():
            if v == c:
                m[k] = d
    #print(m) 
    print("".join(m[c] for c in S))

if __name__ == '__main__':
    main()
