#!/usr/bin/env python3
# from typing import *



# def solve(N: int, S: str, Q: int, c: List[str], d: List[str]) -> str:
def solve(N, S, Q, CD):
    '''chars = list(S)
    for i in range(N):
        for c,d in CD:
            if chars[i] == c:
                chars[i] = d
    '''
    # 置換ルールを辞書で管理
    replace_dict = {c: d for c, d in CD}
    c = list(replace_dict.keys())
    d = list(replace_dict.values())
    
    # 文字列をリストに変換
    char_list = list(S)
    
    # リストを走査して置換
    for i in range(N):
        #print(char_list[i])
        for j, rd in enumerate(c):
            #print(d[j])
            if char_list[i] == rd:
                char_list[i] = d[j]
                #print(char_list)
    #print(char_list)
    # リストを文字列に戻す
    #print(''.join(char_list))
    return ''.join(char_list)

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = input()
    Q = int(input())
    CD = [list(input().split()) for _ in range(Q)]

    ans = solve(N, S, Q, CD)
    print(ans)

if __name__ == '__main__':
    main()
