#!/usr/bin/env python3
# from typing import *


# def solve(K: int) -> Tuple[int, List[int]]:
def solve(K):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    K = int(input())
    N, a = solve(K)
    print(N)
    print(*[a[i] for i in range(N)])


if __name__ == '__main__':
    main()
