#!/usr/bin/env python3
# from typing import *



# def solve(a: int, b: int, c: List[int], d: List[int]) -> List[str]:
import bisect


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = map(int, input().split())
    R = sorted(list(map(int, input().split())))
    for i in range(N - 1):
        R[i+1] += R[i]
    for _ in range(Q):
        x = int(input())
        print(bisect.bisect_right(R, x))

if __name__ == '__main__':
    main()
