#!/usr/bin/env python3
# from typing import *



# def solve(N: int) -> int:
from functools import cache

@cache
def f(N):
    return 0 if N == 1 else f(N // 2) + f((N + 1) // 2) + N

#print(f(int(input())))


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = f(N)
    print(a)

if __name__ == '__main__':
    main()
