#!/usr/bin/env python3
# from typing import *


# def solve(N: int, a: List[int]) -> int:
def solve(N, a):
    a = sorted(a)
    return a[-1]-a[0]


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = list(map(int, input().split()))
    ans = solve(N,a)
    print(ans)


if __name__ == '__main__':
    main()
