#!/usr/bin/env python3
# from typing import *


# def solve(D: int) -> float:
def solve(D):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    D = float(input())
    print(D/100)


if __name__ == '__main__':
    main()
