#!/usr/bin/env python3
# from typing import *


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = S.count('A')
    b = S.count('B')
    c = S.count('C')
    if 'A' * a + 'B' * b + 'C' * c == S:
        print('Yes')
        exit()
    print('No')

if __name__ == '__main__':
    main()
