#!/usr/bin/env python3
# from typing import *

MOD = 1000000007


# def solve(N: int, M: int, f: List[int]) -> int:
def solve(N, M, f):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    f = [None for _ in range(N)]
    for i in range(N):
        f[i] = int(input())
    a = solve(N, M, f)
    print(a)


if __name__ == '__main__':
    main()
