#!/usr/bin/env python3
# from typing import *



# def solve(H: int, W: int, N: int, T: str, S: List[str]) -> int:
def solve(H, W, N, T, S):
    ans = 0
    for i in range(H):
        for j in range(W):
            x, y = j, i
            ok = S[y][x] =="."
            for k in T:
                if not ok:
                    break
                if k == "U":
                    y -= 1
                elif k =="D":
                    y += 1
                elif k =="R":
                    x += 1
                elif k =="L":
                    x -= 1      
                ok &= S[y][x] == "."
            ans += ok 
    return ans

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W, N = map(int, input().split())
    T = input()
    S = [input() for _ in range(H)]
    ans = solve(H, W, N, T, S)
    print(ans)

if __name__ == '__main__':
    main()
