#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <set>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


//auto solve(int64_t N, int T, const std::vector<int64_t> &A, const std::vector<int64_t> &B) {

    //for(int i = 0; i < T; i++){
        
    //}
//}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    int64_t N;
    int T;
    cin >> N >> T;
    vector<int64_t> C(N, 0);
    set<int64_t> values;

    for (int i = 0; i < T; ++i) {
        int64_t A, B;
        cin >> A >> B;
        // 値を更新
        C[A-1] += B;

        // ユニークな値のセットを更新
        values.clear();
        for (int64_t value : C) {
            values.insert(value); // 0の値も含める
        }

        cout << values.size() << '\n';
    }

    return 0;
}
