#!/usr/bin/env python3
# from typing import *

# def solve(N: int) -> Any:
def solve(N):
    for x in range(N+1):
        for y in range(N+1):
            for z in range(N+1):
                if x + y + z < N + 1:
                    print(str(x) +" "+ str(y) +" "+ str(z))


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    solve(N)
    #print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
