#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 1000)  # TODO: edit here
    P = [None for _ in range(N)]
    Q = random.randint(1, 1000)  # TODO: edit here
    C = [None for _ in range(Q)]
    L = [None for _ in range(Q)]
    R = [None for _ in range(Q)]
    X = random.randint(1, 10**9)  # TODO: edit here
    for i in range(N):
        P[i] = random.randint(1, 10**9)  # TODO: edit here
    for i in range(Q):
        C[i] = random.randint(1, 10**9)  # TODO: edit here
        L[i] = random.randint(1, 10**9)  # TODO: edit here
        R[i] = random.randint(1, 10**9)  # TODO: edit here
    print(N, Q, X)
    print(*[P[i] for i in range(N)])
    for i in range(Q):
        print(C[i], L[i], R[i])


if __name__ == "__main__":
    main()
