#!/usr/bin/env python3
# from typing import *


# def solve(N: int, C: List[int]) -> float:
def solve(N, C):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    C = [None for _ in range(N)]
    for i in range(N):
        C[i] = int(input())
    a = solve(N, C)
    print(a)


if __name__ == '__main__':
    main()
