#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, X: int, Y: int, a: List[int], b: List[int]) -> int:
def solve(N, M, X, Y, a, b):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    a = [None for _ in range(N)]
    b = [None for _ in range(M)]
    X = int(next(tokens))
    Y = int(next(tokens))
    for i in range(N):
        a[i] = int(next(tokens))
    for i in range(M):
        b[i] = int(next(tokens))
    assert next(tokens, None) is None
    a1 = solve(N, M, X, Y, a, b)
    print(a1)


if __name__ == '__main__':
    main()
