#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 1000)  # TODO: edit here
    q = [None for _ in range(N)]
    r = [None for _ in range(N)]
    for i in range(N):
        q[i] = random.randint(1, 10**9)  # TODO: edit here
        r[i] = random.randint(1, 10**9)  # TODO: edit here
    Q = random.randint(1, 1000)  # TODO: edit here
    t = [None for _ in range(Q)]
    d = [None for _ in range(Q)]
    for i in range(Q):
        t[i] = random.randint(1, 10**9)  # TODO: edit here
        d[i] = random.randint(1, 10**9)  # TODO: edit here
    print(N)
    for i in range(N):
        print(q[i], r[i])
    print(Q)
    for i in range(Q):
        print(t[i], d[i])


if __name__ == "__main__":
    main()
