#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(int N, int64_t S, int64_t K, const std::vector<int64_t> &P, const std::vector<int64_t> &Q) {
    int sum = 0;
    int temp;
    REP (i, N) {
        temp = P[i] * Q[i];
        sum += temp;
        //cout << P[i] << " " << Q[i] << " " << sum << endl;
    }
    if(sum < S){
        return sum += K;
    }
    else {
        return sum;
    }

}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    int64_t S, K;
    std::cin >> N;
    std::vector<int64_t> P(N), Q(N);
    std::cin >> S >> K;
    REP (i, N) {
        std::cin >> P[i] >> Q[i];
    }
    auto ans = solve(N, S, K, P, Q);
    std::cout << ans << '\n';
    return 0;
}
