#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <queue>
#include <array>
#include <climits>
#include <cmath>
#include <set>
#include <map>
#include <bitset>
#include <deque>
#include <numeric>
#include <assert.h>
#include <unordered_map>
#include <type_traits> // For std::is_floating_point
#include <cmath> // For std::ceil
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(int N, const std::vector<int64_t> &P, const std::vector<int64_t> &Q) {
    vector<int64_t> possible(N);
    int64_t a=0,b=0;
    int64_t cnt = 0;
    for(int64_t i=1; i<=N; i++){
        possible[i-1] = i;
    }
    
    do{
        cnt++;
        if(possible == P){
            a = cnt;
        }
        if(possible == Q){
            b = cnt;
        }
        if(a!=0 && b!=0){
            break;
        }
    }while(next_permutation(possible.begin(), possible.end()));

    return abs(a-b);
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    std::cin >> N;
    std::vector<int64_t> P(N), Q(N);
    REP (i, N) {
        std::cin >> P[i];
    }
    REP (i, N) {
        std::cin >> Q[i];
    }
    auto ans = solve(N, P, Q);
    std::cout << ans << '\n';
    return 0;
}
