#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <queue>
#include <array>
#include <climits>
#include <cmath>
#include <set>
#include <map>
#include <bitset>
#include <deque>
#include <numeric>
#include <assert.h>
#include <unordered_map>
#include <type_traits> // For std::is_floating_point
#include <cmath> // For std::ceil
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t n; cin >> n;
    vector<pair<int64_t, int64_t>> tx(n);
    REP(i, n){
        int64_t t, x;
        cin >> t >> x;
        tx[i] = make_pair(t, x);
    }
    map<int64_t, int64_t> need;
    reverse(ALL(tx));
    vector<int64_t> ans;
    REP(i, n){
        auto [t, x] = tx[i];
        if(t == 1){
            if(need[x]){
                need[x]--;
                ans.push_back(1);
            }
            else{
                ans.push_back(0);
            }
        }
        if(t == 2){
            need[x]++;
        }
    }
    for(auto [k, v]:need){
        if(v != 0){
            cout << -1 << "\n";
            return 0;
        }
    }
    reverse(ALL(ans));
    reverse(ALL(tx));
    int64_t cnt = 0, max_cnt = 0;
    int64_t ans_idx = 0;
    REP(i, n){
        auto [t, x] = tx[i]; 
        if(t == 1){
            if(ans[ans_idx++] == 1){
                cnt++;
                max_cnt = max(max_cnt, cnt);
            }
        } else {
            cnt--;
        }
    }
    cout << max_cnt << "\n";
    for(auto num:ans) cout << num << " ";
    cout << "\n";
    return 0;
}
