#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <queue>
#include <array>
#include <climits>
#include <cmath>
#include <set>
#include <map>
#include <bitset>
#include <deque>
#include <numeric>
#include <assert.h>
#include <unordered_map>
#include <type_traits> // For std::is_floating_point
#include <cmath> // For std::ceil
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;



// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);

    int N;
    cin >> N;
    vector<tuple<int,int,long long>> v;
    v.reserve(N);
    for(int i=0;i<N;i++){
        int t,x; long long a;
        cin >> t >> x >> a;
        v.emplace_back(t,x,a);
    }
    sort(v.begin(), v.end());

    const long long NEG = -(1LL<<60);

    vector<long long> dp(5, NEG), ndp(5, NEG);
    dp[0] = 0;
    int prev = 0;

    for (auto [t,x,a] : v) {
        int dt = t - prev;

        // dt の間に移動できる範囲で遷移（posは5しかないので全探索でOK）
        fill(ndp.begin(), ndp.end(), NEG);
        for(int from=0; from<5; from++){
            if(dp[from]==NEG) continue;
            for(int to=0; to<5; to++){
                if(abs(to-from) <= dt){
                    ndp[to] = max(ndp[to], dp[from]);
                }
            }
        }

        // 捕まえるなら「その時刻に x にいる」必要があるので x だけ加点
        if(ndp[x] != NEG) ndp[x] += a;

        dp.swap(ndp);
        prev = t;
    }

    cout << *max_element(dp.begin(), dp.end()) << "\n";
}
