#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <queue>
#include <array>
#include <climits>
#include <cmath>
#include <set>
#include <map>
#include <bitset>
#include <deque>
#include <numeric>
#include <assert.h>
#include <unordered_map>
#include <type_traits> // For std::is_floating_point
#include <cmath> // For std::ceil
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;



// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t n, m;
    cin >> n >> m;
    vector<int64_t> a(n+1);
    for(int i = 0; i <= n; ++i) {
        cin >> a[i];
    }
    reverse(ALL(a));
    vector<int64_t> c(n+m+1);
    for(int i = 0; i <= n + m; ++i) {
        cin >> c[i];
    }
    reverse(ALL(c));
    vector<int64_t> b(m+1);
    for(int i = 0; i <= m; ++i) {
        b[i] = c[i]/a[0];
        for(int j = 0; j <= n; ++j) {
            c[i+j] -= b[i] * a[j];
        }
    }
    reverse(ALL(b));
    for(int i = 0; i <= m; ++i) {
        cout << b[i] << (i == m ? '\n' : ' ');
    }
    return 0;
}
