#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    M = random.randint(1, 99)  # TODO: edit here
    D = random.randint(1, 99)  # TODO: edit here
    y = random.randint(1000, 9000)  # TODO: edit here
    m = random.randint(1, M)  # TODO: edit here
    d = random.randint(1, D)  # TODO: edit here
    print(M, D)
    print(y, m, d)

if __name__ == "__main__":
    main()
