#!/usr/bin/env python3
# from typing import *


# def solve(S: int, T: int) -> int:
def solve(S, T):
    cnt = 0
    for i in range(S+1):
        for j in range(S+1):
            for k in range(S+1):
                if i+j+k<= S and i*j*k <= T:
                    cnt += 1
    return cnt


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S, T = map(int, input().split())
    a = solve(S, T)
    print(a)


if __name__ == '__main__':
    main()
