#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

def generate_input(N):
    # Initialize the array with -1
    A = [-1] * N
    # Fill the array with a valid sequence that satisfies the constraints
    for i in range(1, N+1):
        while True:
            # Randomly choose an index for person i
            idx = random.randint(0, N-1)
            # If the chosen position is free or if it's the last person (which can go to the only remaining spot)
            if A[idx] == -1 or i == N:
                A[idx] = i
                break
    # Set the first person's position
    A[A.index(N)] = -1
    return N, A


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    '''
    # TODO: edit here
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = random.randint(1, )  # TODO: edit here
    # Print the generated input in the expected format
    '''
    N = random.randint(1, 10)
    N, arrangement = generate_input(N)
    print(N)
    print(' '.join(map(str, arrangement)))

if __name__ == "__main__":
    main()
