#!/usr/bin/env python3
# from typing import *



# def solve(N: int, A: List[int]) -> List[str]:
def solve(N, A):
    posi = list()
    temp = A[0]
    check = True
    change = 0
    while check:
        if change == 0:
            if temp == -1:
                posi = [A.index(temp)+1] + posi
                change = 1
                temp = posi[-1]
            else:
                if len(posi) == 0:
                    posi = [temp] + [A.index(temp)+1]
                else:
                    posi = [temp] + posi
                temp = A[temp-1]
        else:
            posi = posi + [A.index(temp)+1]
        print(posi)
        if len(posi) == N:
            check = False
    return posi


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = list(map(int, input().split()))

    x = 0
    b = [0] * (N + 1)
    for i in range(N):
        if A[i] == -1:
            x = i + 1
        else:
            b[A[i]] = i + 1

    #print(b)

    ans = [x]
    for _ in range(N - 1):
        x = b[x]
        ans.append(x)
    print(*ans)

if __name__ == '__main__':
    main()
