#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 1000)  # TODO: edit here
    P = [[None for _ in range(N)] for _ in range(N)]
    R = [[None for _ in range(N - 1)] for _ in range(N)]
    D = [[None for _ in range(N)] for _ in range(N - 1)]
    for j in range(N):
        for i in range(N):
            P[j][i] = random.randint(1, 10**9)  # TODO: edit here
    for j in range(N):
        for i in range(N - 1):
            R[j][i] = random.randint(1, 10**9)  # TODO: edit here
    for j in range(N - 1):
        for i in range(N):
            D[j][i] = random.randint(1, 10**9)  # TODO: edit here
    print(N)
    for j in range(N):
        print(*[P[j][i] for i in range(N)])
    for j in range(N):
        print(*[R[j][i] for i in range(N - 1)])
    for j in range(N - 1):
        print(*[D[j][i] for i in range(N)])


if __name__ == "__main__":
    main()
