#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <queue>
#include <array>
#include <climits>
#include <cmath>
#include <set>
#include <map>
#include <bitset>
#include <deque>
#include <numeric>
#include <assert.h>
#include <unordered_map>
#include <type_traits> // For std::is_floating_point
#include <cmath> // For std::ceil
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(int N, const std::vector<std::vector<int64_t> > &P, const std::vector<std::vector<int64_t> > &R, const std::vector<std::vector<int64_t> > &D) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    std::cin >> N;
    std::vector<std::vector<int64_t> > P(N, std::vector<int64_t>((N))), R(N, std::vector<int64_t>((N - 1))), D(N - 1, std::vector<int64_t>((N)));
    REP (j, N) {
        REP (i, N) {
            std::cin >> P[j][i];
        }
    }
    REP (j, N) {
        REP (i, N - 1) {
            std::cin >> R[j][i];
        }
    }
    REP (j, N - 1) {
        REP (i, N) {
            std::cin >> D[j][i];
        }
    }
    auto ans = solve(N, P, R, D);
    std::cout << ans << '\n';
    return 0;
}
