#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 10**9)  # TODO: edit here
    M = random.randint(1, 10**9)  # TODO: edit here
    P = random.randint(1, 10**9)  # TODO: edit here
    Q = random.randint(1, 10**9)  # TODO: edit here
    R = random.randint(1, 1000)  # TODO: edit here
    x = [None for _ in range(R)]
    y = [None for _ in range(R)]
    z = [None for _ in range(R)]
    for i in range(R):
        x[i] = random.randint(1, 10**9)  # TODO: edit here
        y[i] = random.randint(1, 10**9)  # TODO: edit here
        z[i] = random.randint(1, 10**9)  # TODO: edit here
    print(N, M, P, Q, R)
    for i in range(R):
        print(x[i], y[i], z[i])


if __name__ == "__main__":
    main()
