#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, P: int, Q: int, R: int, x: List[int], y: List[int], z: List[int]) -> int:
def solve(N, M, P, Q, R, x, y, z):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, P, Q, R = map(int, input().split())
    x = [None for _ in range(R)]
    y = [None for _ in range(R)]
    z = [None for _ in range(R)]
    for i in range(R):
        x[i], y[i], z[i] = map(int, input().split())
    a = solve(N, M, P, Q, R, x, y, z)
    print(a)


if __name__ == '__main__':
    main()
