#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <queue>
#include <array>
#include <climits>
#include <cmath>
#include <set>
#include <unordered_set>
#include <map>
#include <bitset>
#include <deque>
#include <numeric>
#include <assert.h>
#include <stack>
#include <unordered_map>
#include <type_traits> // For std::is_floating_point
#include <cmath> // For std::ceil
#include <cstring>
#include <iomanip>  // 追加: 出力精度を指定するため
#include <tuple>
#include <chrono>
#include <random>
#include <functional>
#include <iterator>
#include <cctype>
#include <limits>
#include <cassert>
#include <complex>
#include <sstream>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
//文字配列の二次元配列みたいなやつを回転させる。
vector<string> rotate90(const vector<string>& matrix) {
    int n = matrix.size();
    int m = matrix[0].size();
    vector<string> rotated(m, string(n, '.'));
    for (int i = 0; i < n; ++i) {
        for (int j = 0; j < m; ++j) {
            rotated[j][n - 1 - i] = matrix[i][j];
        }
    }
    return rotated;
}

// Data structures and algorithms for disjoint set union problems
struct dsu {
  public:
    dsu() : _n(0) {}
    explicit dsu(int n) : _n(n), parent_or_size(n, -1) {}

    int merge(int a, int b) {
        assert(0 <= a && a < _n);
        assert(0 <= b && b < _n);
        int x = leader(a), y = leader(b);
        if (x == y) return x;
        if (-parent_or_size[x] < -parent_or_size[y]) std::swap(x, y);
        parent_or_size[x] += parent_or_size[y];
        parent_or_size[y] = x;
        return x;
    }

    bool same(int a, int b) {
        assert(0 <= a && a < _n);
        assert(0 <= b && b < _n);
        return leader(a) == leader(b);
    }

    int leader(int a) {
        assert(0 <= a && a < _n);
        if (parent_or_size[a] < 0) return a;
        return parent_or_size[a] = leader(parent_or_size[a]);
    }

    int size(int a) {
        assert(0 <= a && a < _n);
        return -parent_or_size[leader(a)];
    }

    std::vector<std::vector<int>> groups() {
        std::vector<int> leader_buf(_n), group_size(_n);
        for (int i = 0; i < _n; i++) {
            leader_buf[i] = leader(i);
            group_size[leader_buf[i]]++;
        }
        std::vector<std::vector<int>> result(_n);
        for (int i = 0; i < _n; i++) {
            result[i].reserve(group_size[i]);
        }
        for (int i = 0; i < _n; i++) {
            result[leader_buf[i]].push_back(i);
        }
        result.erase(
            std::remove_if(result.begin(), result.end(),
                           [&](const std::vector<int>& v) { return v.empty(); }),
            result.end());
        return result;
    }

  private:
    int _n;
    // root node: -1 * component size
    // otherwise: parent
    std::vector<int> parent_or_size;
};

class PrimeSieve {
public:
    PrimeSieve(int max_num) : max_num(max_num), is_prime(max_num + 1, true) {
        run_sieve();
    }

    // 素数判定
    bool isPrime(int num) const {
        if (num < 0 || num > max_num) return false;
        return is_prime[num];
    }

    // 素数のリストを取得
    std::vector<int> getPrimes() const {
        std::vector<int> primes;
        for (int i = 2; i <= max_num; i++) {
            if (is_prime[i]) primes.push_back(i);
        }
        return primes;
    }

private:
    int max_num;
    std::vector<bool> is_prime;

    // エラトステネスの篩を実行
    void run_sieve() {
        is_prime[0] = is_prime[1] = false;
        for (int i = 2; i * i <= max_num; i++) {
            if (is_prime[i]) {
                for (int j = i * i; j <= max_num; j += i) {
                    is_prime[j] = false;
                }
            }
        }
    }
};



// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t h, w;
    std::cin >> h >> w;
    vector<string> s(h);
    REP(i, h) cin >> s[i];
    pair<int, int> start, goal;
    REP(i, h) {
        REP(j, w) {
            if (s[i][j] == 'S') {
                start = {i, j};
            }
            if (s[i][j] == 'G') {
                goal = {i, j};
            }
        }
    }
    vector<pair<int, int>> updown;
    vector<pair<int, int>> leftright;
    updown.push_back({1, 0});
    updown.push_back({-1, 0});
    leftright.push_back({0, 1});
    leftright.push_back({0, -1});
    queue<pair<pair<int, int>, int>> q; // {{x,y}, updown(0) or leftright(1)}
    vector<vector<int64_t>> dist_lastud(h, vector<int64_t>(w, -1));
    vector<vector<int64_t>> dist_lastrl(h, vector<int64_t>(w, -1));
    dist_lastud[start.first][start.second] = 0;
    dist_lastrl[start.first][start.second] = 0;
    q.push({start, -1});
    while(!q.empty()){
        auto p = q.front();
        q.pop();
        int x = p.first.first;
        int y = p.first.second;
        int dir = p.second;
        if (dir != 0) { //1だから右左
            int64_t cur = (dir == 1 ? dist_lastrl[x][y] : dist_lastud[x][y]);
            for (auto d : updown) {
                int nx = x + d.first;
                int ny = y + d.second;
                if (0 <= nx && nx < h && 0 <= ny && ny < w && s[nx][ny] != '#') {
                    int64_t nd = cur + 1;
                    if (dist_lastud[nx][ny] == -1 || dist_lastud[nx][ny] > nd) {
                        dist_lastud[nx][ny] = nd;
                        q.push({{nx, ny}, 0});
                    }
                }
            }
        }
        if (dir != 1) { //0だから上下
            int64_t cur = (dir == 0 ? dist_lastud[x][y] : dist_lastrl[x][y]);
            for (auto d : leftright) {
                int nx = x + d.first;
                int ny = y + d.second;
                if (0 <= nx && nx < h && 0 <= ny && ny < w && s[nx][ny] != '#') {
                    int64_t nd = cur + 1;
                    if (dist_lastrl[nx][ny] == -1 || dist_lastrl[nx][ny] > nd) {
                        dist_lastrl[nx][ny] = nd;
                        q.push({{nx, ny}, 1});
                    }
                }
            }
        }
    }
    int64_t a = dist_lastud[goal.first][goal.second];
    int64_t b = dist_lastrl[goal.first][goal.second];

    if (a == -1 && b == -1) std::cout << -1 << "\n";
    else if (a == -1)       std::cout << b << "\n";
    else if (b == -1)       std::cout << a << "\n";
    else                    std::cout << std::min(a, b) << "\n";
    return 0;
}
