#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <queue>
#include <array>
#include <climits>
#include <cmath>
#include <set>
#include <map>
#include <bitset>
#include <deque>
#include <numeric>
#include <assert.h>
#include <unordered_map>
#include <type_traits> // For std::is_floating_point
#include <cmath> // For std::ceil
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;



// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t n, k; cin >> n >> k;
    vector<int64_t> a(n); 
    vector<int64_t> posi;
    vector<int64_t> nega;
    REP(i, n){
        cin >> a[i];
        if(a[i] == 0) k--;
        if(a[i] > 0) posi.push_back(a[i]);
        if(a[i] < 0) nega.push_back(-a[i]);
    }
    sort(ALL(nega));
    if(k == 0){
        cout << 0 << "\n";
        return 0;
    }
    int64_t INF = 1LL<<60;
    int64_t ans = INF;
    if(posi.size() == 0){
        ans = nega[k-1];
        cout << ans << "\n";
        return 0;
    }
    if(nega.size() == 0){
        ans = posi[k-1];
        cout << ans << "\n";
        return 0;
    }

    if (posi.size()) {
        if ((int64_t)posi.size() >= k) ans = min(ans, posi[k-1]);  // >= に修正
        REP(i, posi.size()) {
            if ((i+1) >= k) break;  // need_neg > 0 が必要
            int64_t need_neg = k - (i+1);
            if (need_neg > (int64_t)nega.size()) continue;  // -1 を削除
            ans = min({ans, posi[i] + 2*nega[need_neg-1], 2*posi[i] + nega[need_neg-1]});
        }
    }
    if (nega.size()) {
        if ((int64_t)nega.size() >= k) ans = min(ans, nega[k-1]);  // >= に修正
        REP(i, nega.size()) {
            if ((i+1) >= k) break;
            int64_t need_pos = k - (i+1);
            if (need_pos > (int64_t)posi.size()) continue;  // -1 を削除
            ans = min({ans, nega[i] + 2*posi[need_pos-1], 2*nega[i] + posi[need_pos-1]});
        }
    }
    cout << ans << "\n";

    return 0;
}
