#!/usr/bin/env python3
# from typing import *


# def solve(A: List[str]) -> Any:
def solve(A):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    values = []
    while input() != 0:
        input_value = int(input())
        values.append(input_value)

    for value in reversed(values):
        print(value)


if __name__ == '__main__':
    main()
