#!/usr/bin/env python3
# from typing import *


# def solve(n: int, x: int) -> int:
def solve(n, x):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    n, x = map(int, input().split())
    a = solve(n, x)
    print(a)


if __name__ == '__main__':
    main()
