#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    
    while True:
        A = random.randint(1, 100)
        B = random.randint(A, 100)
        D = random.randint(1, 100)
        if (B - A) % D == 0 and A!=B:
            return print(A, B, D)

    

if __name__ == "__main__":
    main()
