#!/usr/bin/env python3
# from typing import *



# def solve(S: str) -> Any:
def solve(S):
    i=0
    while i < len(S) - 2:
        if S[i:i+3] == "ABC":
            S = S[:i] + S[i+3:]
            i = max(0, i - 2)  # i の更新
        else:
            i += 1
    return S
    '''
    Origin = S
    for i in range(len(S) - 2):
        if S[i] == "A" and S[i+1] == "B" and S[i+2] == "C":
            S = S[:i] + S[i+3:]
            break
    if Origin == S:
        return S, 0
    else:
        return S, 1
    '''
# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    ans = solve(S)
    print(ans)

if __name__ == '__main__':
    main()
