#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <queue>
#include <array>
#include <climits>
#include <cmath>
#include <set>
#include <map>
#include <bitset>
#include <deque>
#include <numeric>
#include <assert.h>
#include <stack>
#include <unordered_map>
#include <type_traits> // For std::is_floating_point
#include <cmath> // For std::ceil
#include <cstring>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
//文字配列の二次元配列みたいなやつを回転させる。
vector<string> rotate90(const vector<string>& matrix) {
    int n = matrix.size();
    int m = matrix[0].size();
    vector<string> rotated(m, string(n, '.'));
    for (int i = 0; i < n; ++i) {
        for (int j = 0; j < m; ++j) {
            rotated[j][n - 1 - i] = matrix[i][j];
        }
    }
    return rotated;
}

// Data structures and algorithms for disjoint set union problems
struct dsu {
  public:
    dsu() : _n(0) {}
    explicit dsu(int n) : _n(n), parent_or_size(n, -1) {}

    int merge(int a, int b) {
        assert(0 <= a && a < _n);
        assert(0 <= b && b < _n);
        int x = leader(a), y = leader(b);
        if (x == y) return x;
        if (-parent_or_size[x] < -parent_or_size[y]) std::swap(x, y);
        parent_or_size[x] += parent_or_size[y];
        parent_or_size[y] = x;
        return x;
    }

    bool same(int a, int b) {
        assert(0 <= a && a < _n);
        assert(0 <= b && b < _n);
        return leader(a) == leader(b);
    }

    int leader(int a) {
        assert(0 <= a && a < _n);
        if (parent_or_size[a] < 0) return a;
        return parent_or_size[a] = leader(parent_or_size[a]);
    }

    int size(int a) {
        assert(0 <= a && a < _n);
        return -parent_or_size[leader(a)];
    }

    std::vector<std::vector<int>> groups() {
        std::vector<int> leader_buf(_n), group_size(_n);
        for (int i = 0; i < _n; i++) {
            leader_buf[i] = leader(i);
            group_size[leader_buf[i]]++;
        }
        std::vector<std::vector<int>> result(_n);
        for (int i = 0; i < _n; i++) {
            result[i].reserve(group_size[i]);
        }
        for (int i = 0; i < _n; i++) {
            result[leader_buf[i]].push_back(i);
        }
        result.erase(
            std::remove_if(result.begin(), result.end(),
                           [&](const std::vector<int>& v) { return v.empty(); }),
            result.end());
        return result;
    }

  private:
    int _n;
    // root node: -1 * component size
    // otherwise: parent
    std::vector<int> parent_or_size;
};

//listing the prime numbers until N
vector<int64_t> findPrimes(int64_t N) {
    vector<bool> isPrime(N + 1, true);
    isPrime[0] = isPrime[1] = false;
    for (int64_t i = 2; i * i <= N; ++i) {
        if (isPrime[i]) {
            for (int64_t j = i * i; j <= N; j += i) {
                isPrime[j] = false;
            }
        }
    }
    vector<int64_t> primes;
    for (int64_t i = 2; i <= N; ++i) {
        if (isPrime[i]) primes.push_back(i);
    }
    return primes;
}

//Checking given number is prime or not
bool IsPrime(int num)
{
    if (num < 2) return false;
    else if (num == 2) return true;
    else if (num % 2 == 0) return false; // 偶数はあらかじめ除く

    double sqrtNum = sqrt(num);
    for (int i = 3; i <= sqrtNum; i += 2)
    {
        if (num % i == 0)
        {
            // 素数ではない
            return false;
        }
    }
    return true;
}





// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);

    int64_t n; cin >> n;
    string s; cin >> s;
    vector<int64_t> c(n);
    REP(i, n) cin >> c[i];

    vector<int64_t> pre_odd(n+1, 0);  // 0101...
    vector<int64_t> pre_even(n+1, 0); // 1010...
    REP(i, n){
        if(i%2==0){
            pre_odd[i+1]  = pre_odd[i]  + (s[i]=='0' ? 0 : c[i]);
            pre_even[i+1] = pre_even[i] + (s[i]=='1' ? 0 : c[i]);
        } else {
            pre_odd[i+1]  = pre_odd[i]  + (s[i]=='1' ? 0 : c[i]);
            pre_even[i+1] = pre_even[i] + (s[i]=='0' ? 0 : c[i]);
        }
    }

    int64_t total0 = pre_odd[n];
    int64_t total1 = pre_even[n];

    auto suffix_start0 = [&](int j)->int64_t{
        // position j is forced to be 0, then alternate
        if(j%2==0) return total0 - pre_odd[j];   // overall 0101...
        else       return total1 - pre_even[j];  // overall 1010...
    };
    auto suffix_start1 = [&](int j)->int64_t{
        // position j is forced to be 1, then alternate
        if(j%2==0) return total1 - pre_even[j];  // overall 1010...
        else       return total0 - pre_odd[j];   // overall 0101...
    };

    int64_t INF = (1LL<<62);
    int64_t ans = INF;

    for(int i=0;i<=n-2;i++){
        int j = i+1; // start of suffix

        for(int b=0;b<=1;b++){
            // left [0..i], with T[i]=b and alternating
            int start_left = (i%2==0 ? b : 1-b);
            int64_t left = (start_left==0 ? pre_odd[i+1] : pre_even[i+1]);

            // right [j..n-1], with T[j]=b and alternating
            int64_t right = (b==0 ? suffix_start0(j) : suffix_start1(j));

            ans = min(ans, left + right);
        }
    }

    cout << ans << "\n";
}