#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random
import string

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)


def generate_string():
    # 文字列の長さをランダムに選択 (2以上100以下)
    length = random.randint(2, 100)
    # '.'を含む文字列を生成
    s = ''.join(random.choices(string.ascii_lowercase + '.', k=length - 1))
    # 末尾が'.'になるまでランダムにピリオドを追加
    while s.endswith('.'):
        s = s[:-1] + random.choice(string.ascii_lowercase + '.')
    return s

def main():
    # 条件を満たす文字列を生成するまで繰り返す
    while True:
        s = generate_string()
        if '.' in s and not s.endswith('.'):
            print(s)
            break

if __name__ == "__main__":
    main()


