#!/usr/bin/env python3
# from typing import *



# def solve(N: int) -> Any:
def solve(N):
    a = [[0 for _ in range(N)] for _ in range(N)]
    y, x, c = 0, -1, 0
    for i in range(N//2):
        for j in range(N - i*2):
            x += 1
            c += 1
            a[y][x] = c
        for j in range(N - i*2 - 1):
            y += 1
            c += 1
            a[y][x] = c
        for j in range(N - i*2 -1):
            x -= 1
            c += 1
            a[y][x] = c
        for j in range(N - i*2 - 2):
            y -= 1
            c += 1
            a[y][x] = c    
    a[y][x+1] = "T"
    for r in a:
        print(*r)

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    solve(N)


if __name__ == '__main__':
    main()
