#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <queue>
#include <array>
#include <climits>
#include <cmath>
#include <set>
#include <map>
#include <bitset>
#include <deque>
#include <numeric>
#include <assert.h>
#include <unordered_map>
#include <atcoder/all>
#include <type_traits> // For std::is_floating_point
#include <cmath> // For std::ceil
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
using namespace atcoder;

constexpr int64_t MOD = 1000000007;
auto solve(int N, int M, int64_t K, const std::vector<int64_t> &A, const std::vector<int64_t> &X, const std::vector<int64_t> &Y) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, M;
    int64_t K;
    std::cin >> N;
    std::vector<int64_t> A(N);
    std::cin >> M;
    std::vector<int64_t> X(M), Y(M);
    std::cin >> K;
    REP (i, N) {
        std::cin >> A[i];
    }
    REP (i, M) {
        std::cin >> X[i] >> Y[i];
    }
    auto ans = solve(N, M, K, A, X, Y);
    REP (i, N) {
        std::cout << ans[i] << '\n';
    }
    return 0;
}
