#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(int64_t N) {
    int64_t temp = -1;
    for(long long i = 1; i * i * i < N; i++){
        std::string str = std::to_string(i*i*i);
        int j = 0;
        int k = str.length() - 1;
        bool org = true;
        while (j < k) {
            if (str[j] != str[k]) {
                return org = false;
            }
            j++;
            k--;
        }
        if (org){
            if (temp < i*i*i){
                temp = i*i*i;
            }
        }
    }
    return temp;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N;
    std::cin >> N;
    auto ans = solve(N);
    std::cout << ans << '\n';
    return 0;
}
