#!/usr/bin/env python3
# from typing import *



# def solve(S: str) -> int:
def solve(S):

    # Since there are only two different characters, one of them occurs once and the other multiple times.
    for char in S:
        if S.count(char) == 1:
            return S.index(char) + 1  # +1 to adjust index to 1-based indexing
    return -1  # Return -1 or some error code if no unique character found
    '''
    Sl = list(S.split())
    ans = 0
    for l in Sl:
        if Sl.count[l] == 1:
            ans = Sl.index[l]+1

    return ans
    '''
# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)

if __name__ == '__main__':
    main()
