#include <iostream>
#include <string>
#include <vector>
#include <algorithm> // std::countを使用するために必要

#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    std::string S;
    std::cin >> S;
    int output = 0;
    for(std::string::size_type i = 0; i < S.length(); i++){
        int cnt = std::count(S.begin(), S.end(), S[i]);
        //std::cout << cnt << endl;
        if(cnt == 1){
            output = i+1;
            std::cout << output << endl;
            break;
        } 
    }
    return 0;
}
