#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

constexpr int64_t MOD = 998244353;
std::vector<auto> solve(int N, int M, const std::vector<int64_t> &A, const std::vector<int64_t> &L, const std::vector<int64_t> &R, const std::vector<int64_t> &X) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, M;
    std::cin >> N;
    std::vector<int64_t> A(N);
    std::cin >> M;
    std::vector<int64_t> L(M), R(M), X(M);
    REP (i, N) {
        std::cin >> A[i];
    }
    REP (i, M) {
        std::cin >> L[i] >> R[i] >> X[i];
    }
    auto ans = solve(N, M, A, L, R, X);
    REP (i, (int)ans.size()) {
        std::cout << E[i] << ' ';
    }
    std::cout << '\n';
    return 0;
}
