#!/usr/bin/env python3
# from typing import *


# def solve(Deg: int, Dis: int) -> Tuple[str, int]:
def solve(Deg, Dis):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    Deg, Dis = map(int, input().split())
    Dir, W = solve(Deg, Dis)
    print(Dir, W)


if __name__ == '__main__':
    main()
