#!/usr/bin/env python3
# from typing import *



# def solve(N: int) -> str:
def solve(N):
    print('L'+'o'*N + 'n'+'g')


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = solve(N)


if __name__ == '__main__':
    main()
