#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 1000)  # TODO: edit here
    Ax = [None for _ in range(N)]
    Ay = [None for _ in range(N)]
    Bx = [None for _ in range(N)]
    By = [None for _ in range(N)]
    for i in range(N):
        Ax[i] = random.randint(1, 10**9)  # TODO: edit here
        Ay[i] = random.randint(1, 10**9)  # TODO: edit here
    for i in range(N):
        Bx[i] = random.randint(1, 10**9)  # TODO: edit here
        By[i] = random.randint(1, 10**9)  # TODO: edit here
    print(N)
    for i in range(N):
        print(Ax[i], Ay[i])
    for i in range(N):
        print(Bx[i], By[i])


if __name__ == "__main__":
    main()
