#!/usr/bin/env python3
# from typing import *


# def solve(N: int, Ax: List[int], Ay: List[int], Bx: List[int], By: List[int]) -> float:
def solve(N, Ax, Ay, Bx, By):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    Ax = [None for _ in range(N)]
    Ay = [None for _ in range(N)]
    Bx = [None for _ in range(N)]
    By = [None for _ in range(N)]
    for i in range(N):
        Ax[i], Ay[i] = map(int, input().split())
    for i in range(N):
        Bx[i], By[i] = map(int, input().split())
    a = solve(N, Ax, Ay, Bx, By)
    print(a)


if __name__ == '__main__':
    main()
