#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = 0, 1
    while N < M:
        N = random.randint(1, 10 ** 3)  # TODO: edit here
        M = random.randint(1, 10 ** 3)  # TODO: edit here
    S = ''.join([random.choice('012') for _ in range(N)])  # TODO: edit here
    print(N, M)
    print(S)

if __name__ == "__main__":
    main()
