#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 1000)  # TODO: edit here
    A = [None for _ in range(N)]
    S = [None for _ in range(N)]
    for i in range(N):
        A[i] = random.randint(1, 10**9)  # TODO: edit here
    for i in range(N):
        S[i] = ''.join([random.choice('abcde') for _ in range(random.randint(1, 100))])  # TODO: edit here
    Q = random.randint(1, 1000)  # TODO: edit here
    U = [None for _ in range(Q)]
    V = [None for _ in range(Q)]
    for i in range(Q):
        U[i] = random.randint(1, 10**9)  # TODO: edit here
        V[i] = random.randint(1, 10**9)  # TODO: edit here
    print(N)
    print(*[A[i] for i in range(N)])
    for i in range(N):
        print(S[i])
    print(Q)
    for i in range(Q):
        print(U[i], V[i])


if __name__ == "__main__":
    main()
