#!/usr/bin/env python3
# from typing import *


# def solve(O: str, E: str) -> str:
def solve(O, E):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    O = input()
    E = input()
    a = solve(O, E)
    print(a)


if __name__ == '__main__':
    main()
