#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <queue>
#include <array>
#include <climits>
#include <cmath>
#include <set>
#include <map>
#include <bitset>
#include <deque>
#include <numeric>
#include <assert.h>
#include <unordered_map>
#include <type_traits> // For std::is_floating_point
#include <cmath> // For std::ceil
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


vector<int64_t> dirx = {1, 0, -1, 0};
vector<int64_t> diry = {0, 1, 0, -1};

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t n, m; cin >> n >> m;
    vector<string> s(n); REP(i, n) cin >> s[i];
    vector<vector<int64_t>> visited(n, vector<int64_t>(m, 0));
    queue<pair<int64_t, int64_t>> q;
    vector<pair<int64_t, int64_t>> corner;
    q.push({1, 1});
    visited[1][1] = 1;
    corner.push_back({1, 1});
    while(!q.empty()){
        auto [y, x] = q.front(); q.pop();
        for(int i = 0; i < 4; i++){
            int64_t ny = y, nx = x;
            while(s[ny+diry[i]][nx+dirx[i]]=='.'){
                visited[ny][nx]++;
                ny+=diry[i]; nx+=dirx[i];
            }
            if(find(ALL(corner), make_pair(ny, nx))==corner.end()){
                corner.push_back({ny, nx});
                q.push({ny, nx});
            }
        }
    }
    int64_t ans = 0;
    REP(i, n)REP(j, m){
        if(visited[i][j] != 0){
            ans++;
        }
    }
    cout << ans << "\n";
    return 0;
}
