#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(S: str) -> str:
def solve(S):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    cnt = 0
    temp = 0
    if S[0] == "<" and S[-1] == ">":
        if S.count("<") != 1 or S.count(">") != 1:
            print("No")
        else:
            print("Yes")
    else:
        print("No")



if __name__ == '__main__':
    main()
