#!/usr/bin/env python3
# from typing import *


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = list(map(int, input().split()))

    s, m = 0,0
    for x in A:
        s += x
        m = min(m, s)
    print(s-m)
    #print(N)
    #print(A)



if __name__ == '__main__':
    main()
