#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = ''.join([random.choice('abcde') for _ in range(random.randint(1, 100))])  # TODO: edit here
    Q = random.randint(1, 1000)  # TODO: edit here
    T = [None for _ in range(Q)]
    for i in range(Q):
        T[i] = ''.join([random.choice('abcde') for _ in range(random.randint(1, 100))])  # TODO: edit here
    print(S)
    print(Q)
    for i in range(Q):
        print(T[i])


if __name__ == "__main__":
    main()
