#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <queue>
#include <array>
#include <climits>
#include <cmath>
#include <set>
#include <map>
#include <bitset>
#include <deque>
#include <numeric>
#include <assert.h>
#include <unordered_map>
#include <type_traits> // For std::is_floating_point
#include <cmath> // For std::ceil
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;



// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main(){
    int64_t n; cin >> n;
    map<int64_t, int64_t> cnt;
    REP(i, n){
        int64_t a; cin >> a;
        cnt[a]++;
    }
    int64_t total = n*(n-1)*(n-2)/6;
    int64_t bad = 0;
    for(auto&[v,c]:cnt){
        if(c>=2) bad += c*(c-1)/2 * (n-c);
        if(c>=3) bad += c*(c-1)*(c-2)/6;
    }
    cout << total-bad << "\n";
}
