#!/usr/bin/env python3
# from typing import *


# def solve(N: int, W: int, v: List[int], w: List[int]) -> int:
def solve(N, W, v, w):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, W = map(int, input().split())
    v = [None for _ in range(N)]
    w = [None for _ in range(N)]
    for i in range(N):
        v[i], w[i] = map(int, input().split())
    a = solve(N, W, v, w)
    print(a)


if __name__ == '__main__':
    main()
