#!/usr/bin/env python3
# from typing import *


# def solve(N: int, S: int, T: int, W: int, A: List[int]) -> int:
def solve(N, S, T, W, A):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, S, T = map(int, input().split())
    A = [None for _ in range(N - 1)]
    W = int(input())
    for i in range(N - 1):
        A[i] = int(input())
    a = solve(N, S, T, W, A)
    print(a)


if __name__ == '__main__':
    main()
