#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, a: List[int], b: List[int], y: List[int], Q: int, v: List[int], w: List[int]) -> List[str]:
def solve(N, M, a, b, y, Q, v, w):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    a = [None for _ in range(M)]
    b = [None for _ in range(M)]
    y = [None for _ in range(M)]
    for i in range(M):
        a[i], b[i], y[i] = map(int, input().split())
    Q = int(input())
    v = [None for _ in range(Q)]
    w = [None for _ in range(Q)]
    for i in range(Q):
        v[i], w[i] = map(int, input().split())
    c = solve(N, M, a, b, y, Q, v, w)
    for i in range(Q):
        print(c[i])


if __name__ == '__main__':
    main()
