#!/usr/bin/env python3
# from typing import *



# def solve(H: int, W: int, N: int) -> List[str]:
def solve(H, W, N):
    f = [['.'] * W for _ in range(H)] 
    x, y, d = 0, 0, 0
    D = ["U", "R", "D", "L"]
    for i in range(N):
        if f[y][x] == ".":
            f[y][x] = "#"
            d = (d+1)%4
        else:
            f[y][x] = "."
            d = (d-1)%4
        if D[d] == "U":
            y = (y- 1)%H
        elif D[d] == "R":
            x =(x+ 1)%W
        elif D[d] == "D":
            y = (y+1)%H
        else:
            x = (x- 1)%W
    return f

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W, N = map(int, input().split())
    a = solve(H, W, N)
    #print(a)
    for item in a:
        print(''.join(map(str, item)))

if __name__ == '__main__':
    main()
