#!/usr/bin/env python3
# from typing import *


# def solve(s: str, i: int) -> str:
def solve(s, i):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    s = input()
    i = int(input())
    a = solve(s, i)
    print(a)


if __name__ == '__main__':
    main()
