#!/usr/bin/env python3
# from typing import *



# def solve(N: int) -> int:
def solve(N):
    temp = (10**9) // 2
    output = 0
    for i in range(temp):
        if N < 2**i:
            break
        if N % 2 == 1:
            break
        elif (N / 2**i)%2 == 0:
            output += 1
    return output

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = solve(N)
    print(a)

if __name__ == '__main__':
    main()
