#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random
import numpy as np

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # failed to analyze input format
    n = random.randint(2, 10 ** 2)  # TODO: edit here

    # Generate a random 2D array with values 0 or 1
    A = np.random.randint(2, size=(n, n))
    # Set the diagonal to 0 to satisfy the constraint A_i,i = 0
    np.fill_diagonal(A, 0)
    # Make the matrix symmetric to satisfy the constraint A_i,j = A_j,i
    A = np.tril(A) + np.tril(A, -1).T

    print(n)  # TODO: edit here
    for row in A:
        print(' '.join(map(str, row)))

if __name__ == "__main__":
    main()
