#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


//auto solve(int n, const std::vector<int64_t> &a) {
 //   for(int i = 0; i < n; i++){
        
//    }
//}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    // failed to analyze input format
    // TODO: edit here
    int n;
    std::cin >> n;
    vector<vector<int64_t>> a(n, vector<int64_t>(n));

    for (int i = 0; i < n; ++i) {
        for (int j = 0; j < n; ++j) {
            cin >> a[i][j];
            if (a[i][j] == 1){
                std::cout << j+1 << " ";
            }
        }
        std::cout << '\n';
    }

    return 0;
    //for (int i = 0; i < n; i++){
    //    solve(n, a[i]);
    //}

    //REP (i, n) {
    //    std::cin >> a[i];
    //    auto ans = solve(n, a);
        // failed to analyze output format
        // TODO: edit here
    //}
    //std::cout << ans << '\n';//

    
}
