#!/usr/bin/env python3
# from typing import *


# def solve(S: str) -> Tuple[int, int, int, int, int, int]:
def solve(S):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    g, h, m, n, o, p = solve(S)
    print(g, h, m, n, o, p)


if __name__ == '__main__':
    main()
