#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(auto N, auto M, auto L, const std::vector<auto> &a, const std::vector<auto> &b, const std::vector<auto> &c, const std::vector<auto> &d) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    auto N, M, L;
    std::cin >> N;
    std::vector<auto> a(N);
    std::cin >> M;
    std::vector<auto> b(M);
    std::cin >> L;
    std::vector<auto> c(L), d(L);
    REP (i, N) {
        std::cin >> a[i];
    }
    REP (i, M) {
        std::cin >> b[i];
    }
    REP (i, L) {
        std::cin >> c[i] >> d[i];
    }
    auto ans = solve(N, M, L, a, b, c, d);
    std::cout << ans << '\n';
    return 0;
}
